# Generated by Django 6.0.5 on 2026-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirate',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
