# Generated by Django 6.0.5 on 2026-06-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_pirate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pirate',
            name='username',
        ),
    ]
